name: Voting App Workflow

env:
   RGNAME: "AZ-400"

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Azure Login
      uses: Azure/login@v1.4.4
      with:
        # Paste output of `az ad sp create-for-rbac` as value of secret variable: AZURE_CREDENTIALS
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Build the Docker image
      run: |
       ACRSERVERURL=$(az acr list --resource-group $RGNAME --query "[].loginServer" --output tsv)
       ACRNAME=$(az acr list --resource-group $RGNAME --query "[].name" --output tsv)
       NAME="${ACRSERVERURL}/voting-app:latest"
       echo $NAME
       cd azure-vote
       docker build . --file Dockerfile --tag $NAME
       az acr login --name $ACRNAME
       docker push $NAME
    - name: Deploy to Azure Kubernetes
      run: |
       AKSNAME=$(az aks list --resource-group $RGNAME --query "[].name" --output tsv)
       az aks get-credentials --resource-group $RGNAME --name $AKSNAME
       kubectl apply -f azure-vote-all-in-one-redis.yaml

